[package]
name = "ldk-controller"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
nostr-sdk = { git = "https://github.com/dukeh3/nostr.git", rev = "9ac9adc2" }
nwc = { git = "https://github.com/dukeh3/nostr.git", rev = "9ac9adc2" }
bip321 = { git = "https://github.com/DarkWebDivingClub/bip321.git", rev = "fcd4864" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ldk-node = { path = "/home/rene/git/vls/ldk-node" }
ldk-vls2-client = { path = "/home/rene/git/vls/vls-nostr-transport/ldk-vls2-client", features = ["nostr_transport"] }
ldk-vls2-signer = { path = "/home/rene/git/vls/vls-nostr-transport/ldk-vls2-signer" }
lightning-signer = { path = "/home/rene/git/vls/validating-lightning-signer/vls-core", package = "vls-core" }

[dev-dependencies]
testcontainers = "0.27"
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
